version: '3.8'

services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./master_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      --server-id=1
      --log-bin='mysql-bin-1.log'
      --binlog-format='ROW'

  slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./slave_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command:
      --server-id=2
      --relay-log='mysql-relay-bin'
      --log-bin='mysql-bin-2.log'
      --binlog-format='ROW'
    depends_on:
      - master
